#!/usr/bin/perl -w

use strict;
use warnings;
use Time::Local;
use Time::localtime;

use IO::Select;
use IPC::Open3;

#___________________________________________________________
#Скрипт обновляет информацию в Zimbra
#Для работы используеться файл ЕДБО, а таже
#файл с емейлами из зимбры.
#Скрипт проверяет, есть ли в файле с емейлами номер ЕДБО,
#если да, то делает обновление, используя информацию из, 
#файла ЕДБО. Если нет, тогда заносит запись в файл ошибок errorUpd.
#
#
#
#
#__________________________________________________________
# geting data 

#edbo file with information
my $edboFile = "16_17-12-09utf8.csv";
#file with information from zimbra
my $emailUidFile = "UIDMAIL.csv";
#was updated
my $upd = 0;
#cant be updated
my $errUpd = 0;

my %mailUid;
my %nameUid;
my %groupUid;
my %kafUid;
my %specUid;
#name
my $first = "";
my $middle = "";
my $last = "";

my $university = "ХНТУ";
my $city = "Херсон";
my $country = "Україна";
my $stud = "Студент";

my @weekDay = ("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat");
my ($sec, $min, $hour, $mDay, $mon, $year, $wDay) = gmtime(time);
$year += 1900;
$mon += 1;
$hour += 2;

my $data = "$mDay$mon$year";
#logFile
my $logFile = "logUpd"."$data".".dat";
#errorFile
my $error = "errorUpd"."$data".".dat";


print "========================================================\n";
print "                $mDay/$mon/$year  $hour:$min:$sec $weekDay[$wDay]\n";
print "========================================================\n";

open(my $uidFile , "<", "$emailUidFile") || die "Can't open file MAIL: $!\n";
    while(my $line = <$uidFile>){
	chomp($line);
	my ($uid, $email) = split(/\;/, $line);

    	if(exists($mailUid{$uid})) {
            open(my $log, ">>$logFile") || die "Can`t open file $logFile, $!\n";
            print $log "ERROR ZIMBRA: $mailUid{$uid} $uid $email\n";
    	} else {
	    $mailUid{ $uid } = $email;
	}	
    }

open(my $log, ">>", "$logFile") || die "Can't open file: $!\n";
    print $log "File with mail and uid exist and was opened\nfile containt:".scalar(%mailUid)."\n";

#open file EDBO and getting out information,
#checking if uid exists in %mailUidHash, if yes,
#upating information in Zimbra. If no, writing to erroFile.

open(my $edbo, "<", "$edboFile") || die "Can't open file EDBO: $!\n";
while (my $line = <$edbo>){
    chomp($line);
    my ($n, $student_uid, $name, $nameE, $stat, $country, $lang, $var9, $var10, $var11, $year, $date1, $date2,
         $kaf, $va16r, $group1, $course, $var19, $var20, $var21, $var22, $var23, $special) = split(/\;/, $line);

    if(exists($specUid{$student_uid})) {
	#open(my $log, ">>$logFile") || die "Can`t open file $logFile, $!\n"; 
	#print $log "ERROR EDBO SPEC: $n $name  $specUid{$student_uid} $student_uid\n";
    } else {
	$specUid{$student_uid} = $special;
    }

    if(exists($nameUid{$student_uid})) {
	print "ERROR: $n $name $student_uid\n";
	open(my $log, ">>$logFile") || die "Can`t open file $logFile, $!\n";
        print $log "ERROR EDBO NAME: $n $name $nameUid{$student_uid} $student_uid\n";
    } else {
	$nameUid{$student_uid} = $name;
    }

    if(exists($groupUid{$student_uid})) {
	#open(my $log, ">>$logFile") || die "Can`t open file $logFile, $!\n";
	#print $log "ERROR EDBO GROUP: $n $name $groupUid{$student_uid} $student_uid\n";
    } else {
        $groupUid{$student_uid} = $group1;
    }

    if(exists($kafUid{$student_uid})) {
	#open(my $log, ">>$logFile") || die "Can`t open file $logFile, $!\n"; 
        #print $log "ERROR: $n $name $kafUid{$student_uid} $student_uid\n";
    } else {
        $kafUid{$student_uid} = $kaf;
    }
    print "$nameUid{$student_uid} -> $groupUid{$student_uid} -> $kafUid{$student_uid} \n";
}

foreach my $zimbrauid(keys %nameUid) {
    if(exists($mailUid{$zimbrauid})) {
       	print "User exists $mailUid{$zimbrauid} $nameUid{$zimbrauid}\n";
	($first, $last, $middle) = split(/ /, $nameUid{$zimbrauid});
	my $zimbramail = $mailUid{$zimbrauid};
	open(my $tempFile, ">", "/tmp/updtempfile.dat") || die "Can't open file: $!\n";
        print $tempFile "ma $zimbramail title \"$stud\"\n";
        print $tempFile "ma $zimbramail givenName \"$last\"\n";
        print $tempFile "ma $zimbramail sn \"$first\"\n";
        print $tempFile "ma $zimbramail initials \"$middle\"\n";
        print $tempFile "ma $zimbramail displayName \"$first $last\"\n";
        print $tempFile "ma $zimbramail company \"$university\"\n";
        print $tempFile "ma $zimbramail l \"$city\"\n";
        print $tempFile "ma $zimbramail co \"$country\"\n";
        print $tempFile "ma $zimbramail description \"$groupUid{$zimbrauid}\"\n";
	print $tempFile "ma $zimbramail zimbraNotes \"Кафедра $kafUid{$zimbrauid} ($specUid{$zimbrauid})\"\n";
    
	my $upd_user = `su - zimbra -c 'zmprov -f /tmp/updtempfile.dat'`;
        print "User $mailUid{$zimbrauid} was updated\n";
        $upd++;
        open(my $log, ">>", "$logFile") || die "Can't open file: $!\n";
        print $log "User $mailUid{$zimbrauid} exists and updated\n";
    } else {
	print "Can`t find user in file EDOB $nameUid{$zimbrauid} $zimbrauid\n";
        open(my $err, ">>", "$error") || die "Can't open file: $!\n";
        print $err "Not exists $nameUid{$zimbrauid} $zimbrauid\n";
	open (my $log, ">>$logFile") || die "Can`t open file $logFile, $!\n";
	print $log "Not exists $nameUid{$zimbrauid} $zimbrauid\n";
        $errUpd++;
    }
}	

my $sum = $upd + $errUpd;
print "Was updated: $upd\n";
print "Cant update: $errUpd\n";
print "Amount: $sum\n";
